---
resources:
- name: tic-toc
  type: time
  source: {interval: 30m}

jobs:
- name: hello-world
  plan:
  - get: tic-toc
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]

- name: do-some-cool-stuff
  plan:
  - get: tic-toc
    trigger: true
    passed: [hello-world]
  - task: lets-do-it
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        # path: echo
        # args: ["| for i in {1..5}; do printf "ohh yeah $i \n" ; done"]
        path: bash
        args:
        # - -exc
        - -ec
        - |
          whoami
          env
          find .
          echo -e "lets run a for loop in" "\xE2\x9C\x88"
          for i in {1..25}; do printf "ohh yeah, loop run the $i time **** $(date) \n" ; done
          echo -e "thanks for your attention" "\xF0\x9F\xA4\x93"
