apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: concourse-db
  name: concourse-db
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: concourse-db
status:
  loadBalancer: {}
