apiVersion: v1
kind: Service
metadata:
  labels:
    service: concourse-web
  name: concourse-web
spec:
  # clusterIP: None
  ports:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 32080
  selector:
    service: concourse-web
